### ISSUE TITLE
Simple usage in README

### ISSUE THREAD

**Issue by ybiquitous** [mysticatea/eslint-plugin-eslint-comments#17]
Hi! I think more useful if there would be a simple usage of this plugin in README.

The reasons:

- Users can see `node_modules/eslint-plugin-eslint-comments/README.md` on their local machines 
 even if they are off-line.
- Uses can see a simple usage on this repository's top page without one extra click

This is the usage section in the current README:

https://github.com/mysticatea/eslint-plugin-eslint-comments/blob/c427c1c0577fab56f2ff0919053d249938507c83/README.md#-usage

For example:

---

## 📖 Usage

Configure your `.eslintrc.*` file. For example:

```json
{
  "extends": "plugin:eslint-comments/recommended"
}
```

---

What about this suggestion? I would be happy if you would reply. 😃

**Comment by MichaelDeBoey** [comment]
Hi @ybiquitous!

Since this repo is unmaintained, you might want to re-open this issue in the @eslint-community fork https://github.com/eslint-community/eslint-plugin-eslint-comments

For more info about why we created this organization, you can read https://eslint.org/blog/2023/03/announcing-eslint-community-org

**Comment by ybiquitous** [comment]
@MichaelDeBoey Thanks for the reminder! The community fork version has a [great website](https://eslint-community.github.io/eslint-plugin-eslint-comments/), so this issue is no longer needed. 👍🏼
