### ISSUE TITLE
New rule no-uneccessary-globals

### ISSUE THREAD

**Issue by hornta** [mysticatea/eslint-plugin-eslint-comments#20]
We do have a lot of /* globals window */ or /* globals require */ in ourcode despite those being recognized as globals from eslints env and globals config. I suggest having a rule that reports on already existing globals in comments.

**Comment by mysticatea** [comment]
Thank you for this proposal!

However, we cannot implement this without the change of ESLint core. And I think that `no-redeclare` rule should do this because:

- this is a kind of redeclaration.
- `no-unused-vars` rule reports unused variables that `/*globals*/` comments defined.

I opened an issue: https://github.com/eslint/eslint/issues/11370

Please track that issue.
