### ISSUE TITLE
[require-description] duplicated description UX for use with disable-enable-pair

### ISSUE THREAD

**Issue by dimitropoulos** [mysticatea/eslint-plugin-eslint-comments#49]
consider the following example:

```ts
/*eslint eslint-comments/disable-enable-pair: error */
/*eslint eslint-comments/require-description: error */

/*eslint-disable no-undef, no-unused-vars -- My reason for doing this is XYZ */
var foo = bar()
/*eslint-enable no-undef, no-unused-vars -- see above */
```

I love the new `require-description` rule, but I find that in practice, when it's used for `disable-enable-pair` enables... it can be a little clunky.  Any ideas on how to improve the user experience in this case?  Maybe we can give `require-description` an option to `not` require descriptions on `eslint-enable` lines?  Personally, turning a rule back _on_ isn't something I really need a description for so this would work for me.  Any other ideas?

I'm happy to make a PR - just lemme know.

**Comment by MichaelDeBoey** [comment]
Hi @dimitropoulos!

Since this repo is unmaintained, you might want to re-open this issue in the @eslint-community fork https://github.com/eslint-community/eslint-plugin-eslint-comments

For more info about why we created this organization, you can read https://eslint.org/blog/2023/03/announcing-eslint-community-org

**Comment by dimitropoulos** [comment]
sure thing: thanks @MichaelDeBoey for all your work for so many years on this stuff!
