### ISSUE TITLE
`eslint-comments/require-description` should allow ignoring particular rules

### ISSUE THREAD

**Issue by tylerlaprade** [mysticatea/eslint-plugin-eslint-comments#76]
It's very nice that we can ignore categories of `eslint` directives. I would find it very helpful to also be able to ignore particular ESLint rules that we disable for self-evident reasons, such as importing a forbidden library is only allowed in our `ui-component` folder.

**Comment by MichaelDeBoey** [comment]
Hi @tylerlaprade!

Since this repo is unmaintained, you might want to re-open this issue in the @eslint-community fork https://github.com/eslint-community/eslint-plugin-eslint-comments

For more info about why we created this organization, you can read https://eslint.org/blog/2023/03/announcing-eslint-community-org

**Comment by tylerlaprade** [comment]
Moving over to https://github.com/eslint-community/eslint-plugin-eslint-comments/issues/134

**Comment by tylerlaprade** [comment]
Moving over to https://github.com/eslint-community/eslint-plugin-eslint-comments/issues/134
