### ISSUE TITLE
Support for ESLint 9

### ISSUE THREAD

**Issue by Llois41** [mysticatea/eslint-plugin-eslint-comments#81]
Hi,

ESLint 9 is out for while and we'd love to see this plugin with support for ESLint 9 and the flat config.

Any plans of updating this package? Last release is from May 2020 and there still is an open issue for ESLint 8 support.

**Comment by Llois41** [comment]
Update: Seems like https://github.com/eslint-community/eslint-plugin-eslint-comments is the successor of this repo and already is ESLint 9 ready

**Comment by MichaelDeBoey** [comment]
Hi @Llois41!

Since this repo is unmaintained, you might want to re-open this issue in the @eslint-community fork https://github.com/eslint-community/eslint-plugin-eslint-comments

For more info about why we created this organization, you can read https://eslint.org/blog/2023/03/announcing-eslint-community-org
